---
title: "rulemaking_real"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages("editData")
install.packages("readxl")
requires <- c("tidyverse", # tidyverse includes dplyr and ggplot2
              "broom",
              "haven", 
              "devtools",
              "magrittr",
              "margins",
              "lmtest",
              "viridisLite",
              "truncnorm",
              "ggridges",
              "here",
              "fuzzyjoin")
## Install any you don't have
to_install <- c(!requires %in% rownames(installed.packages()))
install.packages(c(requires[to_install], "NA"), repos = "https://cloud.r-project.org/" )
## Load all required R packages
library(tidyverse)
library(broom)
library(haven)
library(magrittr)
library(margins)
library(here)
library(readxl)
library(ggplot2); theme_set(theme_bw()) # global plot theme
## Colorblind and greyscale print-friendly scales
library(viridisLite)
  options(
    ggplot2.continuous.color = "viridis",
    ggplot2.continuous.fill = "viridis"
  )
  scale_color_discrete <- function(...)
    scale_color_viridis_d(..., begin = 0, end = .7)
  scale_fill_discrete <- function(...)
    scale_fill_viridis_d(..., begin = 0, end = .7)
  
```

```{r data}
library(googlesheets4)
comments <- read_sheet("https://docs.google.com/spreadsheets/d/1HBjG32qWVdf9YxfGPEJhNmSw65Z9XzPhHdDbLnc3mYc/edit?usp=sharing")
load("/Users/samihabhushan/Documents/financial-rulemaking/data/members.Rdata")
agency_data <- read_excel("/Users/samihabhushan/Documents/financial-rulemaking/data/federal_agencies_list.xlsx")
```


```{r president_scores}
members %<>% 
  mutate(nominate_pres = case_when(
  congress < 111 ~ 0.693,
  congress >111 & congress <115 ~ -0.358,
  congress > 115 & congress <117 ~ 0.403,
  congress > 117 ~ -0.320))

members %<>% mutate(
nominate_diff = nominate.dim1-nominate_pres)

comments %<>% full_join(members, by = "icpsr", copy = TRUE)
comments %<>% mutate(agency = str_remove(docket_id, "-.*") )
comments %<>% full_join(agency_data, by = c("agency"="Acronym"))
```
## Real data model

Does the model, $y_i = \beta_0 + \beta_1*party_i + \epsilon_i$, test the relationship of interest? 

```{r congress_ols_estimate}
congressional_success <- comments$success
model <- lm(congressional_success ~ nominate_diff, data = comments) 
m <- model %>% 
  tidy(conf.int = TRUE) 
m
ggplot(m %>% filter(term != "(Intercept)")) + 
  aes(x = term,
      y = estimate, 
      ymin = conf.low, 
      ymax = conf.high) + 
  geom_pointrange() + 
  geom_hline(yintercept = 0, color = "grey") + 
  coord_flip() + 
  labs(x="", y="OLS Estimate")

```
